booksapp/urls.py
from django.urls import path
from . import views
app_name = "booksapp"
urlpatterns = [
    path('addbook/', views.addbook, name='addbook'),
    path('detail/<int:pk>', views.BookDetailView.as_view(), name='detail'),
    path('deletebook/<int:pk>/', views.deletebook, name='deletebook'),
    path("category",views.category, name="category" ),
    path('search/', views.lsearch, name='search'),
    path('updatebook/<int:pk>', views.LEditView.as_view(), name='updatebook'),
]

home/urls.py
from . import views
from django.urls import path
app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
]

library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls", namespace="users")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("home.urls", namespace="home")),
    path("", include("booksapp.urls", namespace="booksapp")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path,include,re_path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"   


urlpatterns = [
    path('api/profile',views.ProfileList.as_view()),
    path('profile/',views.profile,name = 'profile'),
    #path('user_profile/',views.user_profile,name = 'user_profile'),
    path('edit_profile/',views.edit_profile,name = 'edit_profile'), 
    path("register/", views.register, name="register"),
    path('profile/',views.profile,name = 'profile'),

    

]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from booksapp.models import Book
from django.views.generic import CreateView, DetailView, DeleteView, UpdateView, ListView
# Create your views here.
def index(request):

    books = Book.objects.all()
    return render(request, "index.html", {"books": books})

home/templates/footer.html
<footer class="text-center text-white" style="background-color: #f1f1f1;">
    <!-- Grid container -->
    <div class="container pt-4">
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Facebook -->
        <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-facebook-f"></i
        ></a>
  
        <!-- Twitter -->
        <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-twitter"></i
        ></a>
  
        <!-- Google -->
        <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-google"></i
        ></a>
  
        <!-- Instagram -->
        <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-instagram"></i
        ></a>
  
        <!-- Linkedin -->
        <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-linkedin"></i
        ></a>
        <!-- Github -->
        <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-github"></i
        ></a>
      </section>
      <!-- Section: Social media -->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>

home/templates/index.html
{% extends "base.html" %}
{% block content %}
{% include "navbar.html" %}


    


<div class="container-fluid">
    <div class="row" style="padding-top: 87px">
    
    <div class="col-sm-1" style="color: red">
    </div>
    
    
    <div class="col-sm-10">
                    <div class="card mb-3">
                    <div class="card-header">
                        <i class="fas fa-table text-primary"></i>
                        Recent Added Books
                    </div>
                    <div class="card-body">
                       <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="#"></a>
    
                        <a  class="btn btn-sm btn-success" href="{% url 'booksapp:addbook' %}" style="padding: 8px; float: right; background-color: green; color: white;">Add Book</a>
                    </li>
                </ol>
    
                 {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                <div class="card mb-3">
    
                    <div class="card-body">
                        <div class="table-responsive">
    <!-- Table --->
    
    
                         
                             <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Book ID</th>
                                    <th>Book Cover</th>
                                    <th>Book Title</th>
                                    <th>Read</th>
                                    <th>Download</th>
                                    <th>Category</th>
                                    <th>Ratings</th>
                                 
                                </tr>
                                </thead>
                                <tbody>
    
    
                               <!-- if and for -->
                               {% if books %}
                               {% for book in books %}
    
                            
                                    <tr>
                                      <td><a href="{% url 'booksapp:detail' book.pk %}">{{book.id}}</a></td>
                                      <td>
                                        {% if book.cover %}
                                        <img src="{{ book.cover.url }}" alt="{{ book.title}}" style="height: 100px; width: 100px">
                                        {% else %}
                                        <span class="text-muted">No Cover</span>
                                        {% endif %}
                                       </td>
                                      <td>{{ book.title }}</td>
                                        <td>
                                            {% if book.pdf %}
                                        <a href="{{ book.pdf.url }}" class="btn btn-outline-primary" target="_blank">View PDF</a>
                                        {% else %}
                                        <span class="text-muted">No PDF</span>
                                        {% endif %}
                                      </td>
    
    
                                        <td>
                                            {% if book.pdf %}
                                        <a href="{{ book.pdf.url }}" download class="btn btn-outline-success">Download PDF</a>
                                        {% else %}
                                        <span class="text-muted">No PDF</span>
                                        {% endif %}
                                        
                                      </td>
                                      
                                    </tr>
    
                                    <!-- end for and if -->
                                    {% endfor %}
                                   {% endif %} 
                                </tbody>
                            </table>
    
     
    
</div></div></div></div></div></div></div></div>

                            {% include "footer.html" %}


{% endblock %}

home/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light py-4">
	<div class="container-fluid">
		<a class="navbar-brand" href="https://library.livecanvas.com/sections/">
			<img class="img-fluid" src="https://getbootstrap.com/docs/5.1/assets/brand/bootstrap-logo.svg" alt="" width="48px" height="48px">
		</a>Book Library
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav_lc" aria-controls="nav_lc" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="nav_lc">
			<ul class="navbar-nav my-3 my-lg-0 ms-lg-3 me-auto">
				<li class="nav-item me-4"><a class="nav-link" href="{% url 'home:index' %}">Home</a></li>

				<li class="nav-item me-4"><a class="nav-link" href="{% url 'booksapp:addbook' %}">Upload Book</a></li>
				<form action="{% url 'booksapp:search' %}" class="d-flex searchitem"> <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"> <i class="fa fa-search"></i> </form>
             
			</ul>
            
			<div>
				{% if user.is_authenticated %}
				<a class="btn btn-outline-secondary me-2" href="{% url 'users:profile' %}">{{user.username}}</a>
                <a class="btn btn-primary" href="{% url 'users:register' %}">Logout</a>
				{% else %}
				<a class="btn btn-outline-secondary me-2" href="{% url 'login' %}">Sign In</a>
                <a class="btn btn-primary" href="{% url 'users:register' %}">Sign Up</a>
				{% endif %}
            </div>
		</div>
	</div>
</nav>