booksapp/urls.py
from django.urls import path
from . import views
app_name = "booksapp"
urlpatterns = [
    path('addbook/', views.addbook, name='addbook'),
    path('detail/<int:pk>', views.BookDetailView.as_view(), name='detail'),
    path('deletebook/<int:pk>/', views.deletebook, name='deletebook'),
    path("category",views.category, name="category" ),
    path('search/', views.lsearch, name='search'),
    path('updatebook/<int:pk>', views.LEditView.as_view(), name='updatebook'),
]

home/urls.py
from . import views
from django.urls import path
app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
]

library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls", namespace="users")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("home.urls", namespace="home")),
    path("", include("booksapp.urls", namespace="booksapp")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

booksapp/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    year = models.CharField(max_length=100)
    publisher = models.CharField(max_length=200)
    desc = models.CharField(max_length=1000)
    uploaded_by = models.CharField(max_length=100, null=True, blank=True)
    user_id = models.CharField(max_length=100, null=True, blank=True)
    pdf = models.FileField(upload_to='bookapp/pdfs/')
    cover = models.ImageField(upload_to='bookapp/covers/', null=True, blank=True)

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.pdf.delete()
        self.cover.delete()
        super().delete(*args, **kwargs)        

booksapp/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'publisher', 'year', 'uploaded_by', 'desc', 'pdf', 'cover')        

booksapp/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Book
from .forms import BookForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import CreateView, DetailView, DeleteView, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from . import models
import operator
import itertools
from django.urls import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
@login_required
def addbook(request):
    """
    addbook function
    """
    if request.method=="POST":
        form = BookForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            blogpost = form.save(commit=False)
            blogpost.author = request.user
            blogpost.save()
            obj = form.instance
            alert = True
            return redirect('home:index')  
    else:
        form=BookForm()
    return render(request, "books/add_book.html", {'form':form})


class BookDetailView(LoginRequiredMixin,DetailView):
    model = Book
    template_name = 'books/book_detail.html'
    context_object_name = 'object'



def deletebook(request, id):
    book = get_object_or_404(Book, id=id) 
    book.delete()
    return redirect('home:index')


def category(request):
    return render(request, "books/category.html")




@login_required
def lsearch(request):
    query = request.GET['query']
    print(type(query))


    #data = query.split()
    data = query
    print(len(data))
    if( len(data) == 0):
        return redirect('home:index')
    else:
                a = data

                # Searching for It
                qs5 =models.Book.objects.filter(id__iexact=a).distinct()
                qs6 =models.Book.objects.filter(id__exact=a).distinct()

                qs7 =models.Book.objects.all().filter(id__contains=a)
                qs8 =models.Book.objects.select_related().filter(id__contains=a).distinct()
                qs9 =models.Book.objects.filter(id__startswith=a).distinct()
                qs10 =models.Book.objects.filter(id__endswith=a).distinct()
                qs11 =models.Book.objects.filter(id__istartswith=a).distinct()
                qs12 =models.Book.objects.all().filter(id__icontains=a)
                qs13 =models.Book.objects.filter(id__iendswith=a).distinct()




                files = itertools.chain(qs5, qs6, qs7, qs8, qs9, qs10, qs11, qs12, qs13)

                res = []
                for i in files:
                    if i not in res:
                        res.append(i)


                # word variable will be shown in html when user click on search button
                word="Searched Result :"
                print("Result")

                print(res)
                files = res




                page = request.GET.get('page', 1)
                paginator = Paginator(files, 10)
                try:
                    files = paginator.page(page)
                except PageNotAnInteger:
                    files = paginator.page(1)
                except EmptyPage:
                    files = paginator.page(paginator.num_pages)
   


                if files:
                    return render(request,'books/results.html',{'files':files,'word':word})
                return render(request,'books/results.html',{'files':files,'word':word})


	
class LEditView(LoginRequiredMixin,UpdateView):
	model = Book
	form_class = BookForm
	template_name = 'books/editbook.html'
	success_url = reverse_lazy('home:index')
	success_message = 'Data was updated successfully'

booksapp/templates/books/add_book.html
{% extends 'base.html' %}

{% block content %}

 
{% load crispy_forms_tags %}
  <div class="container" style="margin-top: 5rem; margin-bottom: 8rem; ">
    <div class="row justify-content-md-center ">
          <div class="col col-lg-5 border">
          <h2 class="text-center">Add book</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{form | crispy}}
        <center><button class="btn btn-outline-info" value="addbook" type="submit">Submit</center>
    </form>
    
      </div>
    </div>
  
 </div>
   
{% endblock %}

booksapp/templates/books/book_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include "navbar.html" %}


    
<div class="container">
        <div class="row">
          <div class="col-12 mb-1">
          <div class="col-12 mb-1">
              <div id="content-wrapper">
        <div class="container-fluid">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="">book Title : {{ object.title }} </a>
            </ol>
            <div class="card mb-3">
                <div class="card-header">
                    <i class="fas fa-table text-warning"></i>
                    Details Of Book
                </div>
                <div class="card-body">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}

 <div class="row">
        <div class="col-12">
            <ul class="list-group">
              <li class="list-group-item"><strong>Book Title:</strong> {{ object.task_title }}</li>
              <li class="list-group-item"><strong>Author :</strong> {{ object.author }}</li>
              <li class="list-group-item"><strong>Description:</strong> {{ object.desc }}</li>
              <li class="list-group-item"><strong>Uploded By :</strong> {{ object.uploaded_by }}</li>
            </ul>
        </div>
    </div>

    <div class="row top-buffer" style="padding-top: 10px">
        <div class="col-12">
                <a href=""><button type="button" class="btn btn-success">Edit</button></a>
                <a href=""><button type="button" class="btn btn-outline-secondary">Delete</button></a>
                
        </div>
    </div>


          </div>
        </div>
      </div>
    </div>
    </div>
          </div></div></div>    {% include "footer.html" %}


    
{% endblock %}

booksapp/templates/books/books_list.html
{% for book in books %}
{{book.title}}
{% endfor %}

booksapp/templates/books/category.html
{% extends 'base.html' %}

{% block content %}
{% include "navbar.html" %}

<div class="container">

    <div class="row mt-2 g-3 ">
        <div class="col-md-3">
            <div class="card p-1">
                <p class="text-right">d</p>
                <div class="d-flex justify-content-between align-items-center p-2">
                    <div class="flex-column lh-1 imagename "> <span>Mobile</span> <span>Phones</span> </div>
               
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card p-2">
                <div class="d-flex justify-content-between align-items-center p-2">
                    <div class="flex-column lh-1 imagename"> <span>Head</span> <span>Phones</span> </div>
                    <div> <img src="https://i.imgur.com/SHWASPG.png" height="100" width="100" /> </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card p-2">
                <div class="d-flex justify-content-between align-items-center p-2">
                    <div class="flex-column lh-1 imagename"> <span>Smart</span> <span>Watches</span> </div>
                    <div> <img src=" https://i.imgur.com/Ya0OXCv.png" height="100" width="100" /> </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card p-2">
                <div class="d-flex justify-content-between align-items-center p-2">
                    <div class="flex-column lh-1 imagename"> <span>Air</span> <span>Purifiers</span> </div>
                    <div> <img src="https://i.imgur.com/2gvGwbh.png" height="100" width="100" /> </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card p-2tr5">
                <div class="d-flex justify-content-between align-items-center p-2">
                    <div class="flex-column lh-1 imagename"> <span>Vacuum</span> <span>Cleaners</span> </div>
                    <div> <img src="https://i.imgur.com/UMQJpSG.png" height="100" width="100" /> </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card p-2">
                <div class="d-flex justify-content-between align-items-center p-2">
                    <div class="flex-column lh-1 imagename"> <span>Washing</span> <span>Machines</span> </div>
                    <div> <img src="https://i.imgur.com/e9CyhXR.png" height="100" width="100" /> </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card p-2">
                <div class="d-flex justify-content-between align-items-center p-2">
                    <div class="flex-column lh-1 imagename"> <span>Smart</span> <span>Televisions</span> </div>
                    <div> <img src=" https://i.imgur.com/Zq8VigZ.png" height="100" width="100" /> </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card p-2">
                <div class="d-flex justify-content-between align-items-center p-2">
                    <div class="flex-column lh-1 imagename"> <span>Laptops</span> </div>
                    <div> <img src="https://i.imgur.com/6pK5oZl.jpg" height="100" width="100" /> </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include "footer.html" %}

{% endblock %}

booksapp/templates/books/delete.html
{% extends 'base.html' %} 


{% block content %} 

    <form action="" method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{obj}}"?</p>
        <a href="{{ request.META.HTTP_REFERER }}">go back</a>
        <input type="submit" value='confirm'>
    </form>

{% endblock %}

booksapp/templates/books/editbook.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="container-fluid">
        <div class="row">
          <div class="col-12 mb-3">
          <div class="col-12 mb-3">
              <div id="content-wrapper">
        <div class="container-fluid">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="">Book Title : {{ object.title }} </a>
            </ol>
            <div class="card mb-3">
                <div class="card-header">
                    <i class="fas fa-table text-warning"></i>
                    Details Of Book
                </div>
                <div class="card-body">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}

    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}
                <input type="submit" {% if request.path == '/new' %} value="Add" {% else %} value="Update" {% endif %} class="btn btn-success"/>
                <a href="{% url 'booksapp:updatebook' %}"><button type="button" class="btn btn-secondary">Back</button></a>
            </form>
        </div>
    </div>


          </div>
        </div>
      </div>
    </div>
{% endblock %}

booksapp/templates/books/results.html
{% extends 'base.html' %}
{% block body %}


<div class="container-fluid">
<div class="row" style="padding-top: 30px">

<div class="col-sm-1" style="color: red">
</div>

<div class="col-sm-10">
            <div class="card mb-3">
                <div class="card-body">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                   

                        
                        <ol class="breadcrumb">
      <li class="breadcrumb-item">
            <a href="#">BookApp Search Results</a>
      </li>
</ol>


                    {% if files %}

                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Book Cover</th>
                                <th>Book Title</th>
                                <th>Publisher</th>
                                <th>Read</th>
                                <th>Download</th>
                                <th>Delete</th>
                            </tr>
                            </thead>
                            <tbody>


                                  {% for file in files %}

                        
                                <tr>
                                  <td>{{ file.id }}</td>
                                  <td>
                                    {% if file.cover %}
                                    <img src="{{ file.cover.url }}" alt="{{ file.title }}" style="width:100px; height: 100px">
                                    {% else %}
                                    <span class="text-muted">No cover</span>
                                    {% endif %}
                                   </td>

                                  
                                  <td>{{ file.title }}</td>
                                  <td>{{ file.uploaded_by }}</td>


                                    <td>
                                    {% if file.pdf %}
                                      <a href="{{ file.pdf.url }}" class="btn btn-outline-primary" target="_blank">
                                    View PDF</a>
                                    {% else %}
                                    <span class="text-muted">No PDF</span>
                                   {% endif %}
                                  </td>
                                    <td>
                                    {% if file.cover %}
                                      <a href="{{ file.pdf.url }}" download class="btn btn-outline-success">
                                    Download PDF</a>
                                    {% else %}
                                   <span class="text-muted">No PDF</span>
                                   {% endif %}
                                  </td>

        <td>
          <a href="{% url 'ldbook' file.pk %}"><button type="button" class="btn btn-danger"> Delete</button></a></td>
                                  
                                </tr>

                                <!-- end for and if -->
                                {% endfor %}
                            </tbody>
                        </table>


                        {%else%}


<center><h3 style="text-align:center; color:yellow; background: green; width: 600px" id="answer">No Search Found</h3></center>

                <style type="text/css">
                  #search_result {
                 display: none;
                 }
    </style>

                       {%endif%}    
                            </tbody>
                        </table>

                        {% if files.has_other_pages %}
    <ul class="pagination">
        {% if files.has_previous %}
            <li class="waves-effect"><a href="?page=
                    {{ files.previous_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}"><i
                    class="material-icons text-primary">&laquo;</i></a></li>
        {% else %}
            <li class="disabled"><a href="#!"><i class="material-icons text-primary">&laquo;</i></a></li>
        {% endif %}
        {% for num in files.paginator.page_range %}
            {% if files.number == num %}
                <li class="active"><a href="#!">{{ num }}</a></li>
            {% else %}
                <li class="waves-effect"><a
                        href="?page={{ num }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}
        {% if files.has_next %}
            <li class="waves-effect"><a
                    href="?page={{ files.next_page_number }}{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}"><i
                    class="material-icons">&raquo;</i></a></li>
        {% else %}
            <li class="disabled"><a href="#!"><i class="material-icons">&raquo;</i></a></li>
        {% endif %}
    </ul>
{% endif %}




                    </div>
                </div>
            </div>
        </div>
    </div>



        
          </div>
        </div>
      </div>
    </div>

{% endblock body %}

{% block extrascripts %}
  <script type="text/javascript">
  </script>
{% endblock extrascripts %}